#!/bin/bash

VULKANINFO="/usr/bin/vulkaninfo"

# Ensure a valid display is set
if [ -z "$WAYLAND_DISPLAY" ]; then
    if [ -z "$DISPLAY" ]; then
        export DISPLAY="$(getLocalXDisplay)"
    fi
fi

# Check if vulkaninfo exists
if [ ! -e "$VULKANINFO" ]; then
    echo "Vulkan not found"
    exit 1
fi

VK_OUT="$("$VULKANINFO" 2>/dev/null)"

# Function to list Vulkan GPU devices
list_devices() {
    printf '%s\n' "$VK_OUT" | grep 'deviceName' | awk -F'= ' '{print $2}'
}

# Function to count the number of Vulkan GPU devices
num_devices() {
    list_devices | wc -l
}

# Function to check if Vulkan is available
has_vulkan() {
    if printf '%s\n' "$VK_OUT" | grep -q 'deviceName'; then
        echo "true"
    else
        echo "false"
    fi
}

vulkan_version() {
    apiVersion="$(printf '%s\n' "$VK_OUT" | awk '/apiVersion/ {print $3; exit}')"
    if [ -n "$apiVersion" ]; then
      echo "$apiVersion"
      return 0
    fi
    echo "No Vulkan driver found!"
}

# Handle input options
case "$1" in
    "listDevices")
        list_devices
        ;;
    "numDevices")
        num_devices
        ;;
    "hasDiscrete")
        # Knulli will probably never have descrete gpu's
        echo "false"
        ;;
    "discreteUUID"|"discreteName"|"discreteIndex")
        exit 1
        ;;
    "hasVulkan")
        has_vulkan
        ;;
    "vulkanVersion")
        vulkan_version
        ;;
    *)
        echo "Invalid option. Usage: $0 {listDevices|numDevices|hasDiscrete|discreteUUID|discreteName|discreteIndex|hasVulkan|vulkanVersion}"
        exit 1
        ;;
esac
