#!/bin/sh

# Check if knulli-brightness command exists
command -v knulli-brightness >/dev/null || exit 0

case $1 in
    start)
        # Retrieve the current brightness setting
        BRI=$(knulli-settings-get display.brightness)

        # Check if the command was successful and handle accordingly
        if [ $? -eq 0 ]; then
            # If brightness is less than 1, set it to 1 // 1 is the new min brightness
            if [ "$BRI" -lt 1 ]; then
                BRI=1
            fi
        else
            # If no value is found, set brightness to 50%
            BRI=50
        fi

        knulli-brightness "$BRI"
        ;;
    stop)
        # Get brightness values
        # Determine current brightness from file or fallback to knulli-brightness
        if [ -f "/var/run/knulli-brightness" ]; then
            read -r CURRENT_BRI < /var/run/knulli-brightness
        else
            CURRENT_BRI=$(knulli-brightness)
        fi

        SAVED_BRI=$(knulli-settings-get display.brightness)

        # Update saved brightness setting if it's different from the current brightness
        if [ "$SAVED_BRI" != "$CURRENT_BRI" ]; then
            if [ -e "/userdata/system/knulli.conf" ]; then
                knulli-settings-set-queue display.brightness "$CURRENT_BRI"
            fi
        fi
        ;;
esac

exit 0
