LABEL knulli.linux
LINUX /boot/Image
FDT /boot/rk3576-anbernic-rg-vita-pro.dtb
APPEND initrd=/boot/initrd.lz4 label=KNULLI rootwait quiet loglevel=0 console=tty3 console=ttyS2,1500000n8 fbcon=rotate:1
