#!/bin/sh

BATTERYSAVER_VAR_FOLDER="/var/run/battery-saver"
BATTERYSAVER_VAR_FILE="$BATTERYSAVER_VAR_FOLDER/00batterysaver-chargingbypass.pause"

KEY_CHARGING_BYPASS="system.batterysaver.chargingbypass"

pause() {
    mkdir -p "$BATTERYSAVER_VAR_FOLDER"
    touch "$BATTERYSAVER_VAR_FILE"
}

unpause() {
    rm -f "$BATTERYSAVER_VAR_FILE"
}

# If device is discharging, remove the batterysaver unpause and exit.
if [ "$1" = "Discharging" ]; then
    unpause
    exit 0
fi

# If charging bypass is disabled, unpause and exit.
CHARGING_BYPASS="$(knulli-settings-get "$KEY_CHARGING_BYPASS" 2>/dev/null)"

if [ -z "$CHARGING_BYPASS" ] || [ "$CHARGING_BYPASS" -eq 0 ]; then
    unpause
    exit 0
fi

# The device is not discharging and the bypass is enabled, so we need to pause.
pause

exit 0
