KEY_VOLUMEUP 1               -audio setSystemVolume +5
KEY_VOLUMEDOWN 1             -audio setSystemVolume -5
KEY_POWER 1                  /usr/bin/power-button
KEY_POWER 0                  /usr/bin/power-button-release
KEY_VOLUMEUP+BTN_TL2 1       -brightness + 5
KEY_VOLUMEDOWN+BTN_TL2 1     -brightness - 5
KEY_POWER+BTN_TL2 1          /usr/bin/power-led
BTN_TL 1                     /usr/bin/dpad-toggle
BTN_TL 0                     /usr/bin/dpad-toggle-release
BTN_TL+BTN_TL2 1             /usr/bin/knulli-game-switcher
