#!/bin/bash

ZRAM_DEV="/dev/zram0"
ZRAM_SYS="/sys/block/zram0"

start() {
    /sbin/modprobe zram 2>/dev/null || true

    # Check if compatible
    [ -e "$ZRAM_DEV" ] || {
        curl -s -X POST http://127.0.0.1:1234/messagebox -d "Device not compatible." >/dev/null 2>&1
        knulli-services disable zramswap
        exit 1
    }

    echo lz4 > "$ZRAM_SYS/comp_algorithm" 2>/dev/null \
    || echo lzo > "$ZRAM_SYS/comp_algorithm" 2>/dev/null || true

    totalmem=$(free -b | grep -m1 "^Mem:" | tr -s ' ' | cut -d ' ' -f2)
    swapmem=$(( totalmem  / 2 ))

    echo "$swapmem" > "$ZRAM_SYS/disksize" || exit 1
    /sbin/mkswap "$ZRAM_DEV" || exit 1
    /sbin/swapon -p 1000 "$ZRAM_DEV" || exit 1

    echo 100 > /proc/sys/vm/swappiness
    echo 0   > /proc/sys/vm/page-cluster
}

stop() {
    [ -e "$ZRAM_DEV" ] || exit 0
    /sbin/swapoff "$ZRAM_DEV" >/dev/null 2>&1 || true
    /sbin/modprobe -r zram >/dev/null 2>&1 || true
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac

exit $?
