#!/bin/sh

BIN="/usr/bin/trimui_inputd"
[ -f "$BIN" ] || exit 0

read -r BOARD < /boot/boot/knulli.board
case "$BOARD" in
    trimui-smart-pro|trimui-brick|trimui-smart-pro-s)
        ;;
    *)
        exit 0
        ;;
esac

case "$1" in
    start)
        "$BIN" &
        ;;
    stop)
        killall -9 trimui_inputd 2>/dev/null || true
        ;;
esac

exit 0

