#!/bin/bash

do_usage() {
    echo "$1 list"
    echo "$1 get"
    echo "$1 set {auto|<device>}"
    echo "$1 list-profiles"
    echo "$1 get-profile"
    echo "$1 set-profile {auto|<profile>}"
    echo "$1 getSystemVolume"
    echo "$1 setSystemVolume {mute|unmute|mute-toggle|[+-]<0...100>}"
    echo "$1 test"
}

# Export XDG for PW
export XDG_RUNTIME_DIR=/var/run

# Set variables
MAX_VOLUME="$(/usr/bin/knulli-settings-get audio.volume.boost)" || MAX_VOLUME=100
DEFAULT_SINK=$(LANG=C pactl info | grep -E '^Default Sink: ' | sed -e s+"^Default Sink: "+""+ | head -1)
DETECT_VOLUME=$(LANG=C pactl list sinks-raw | grep -E '^[^ ]* name="'"${DEFAULT_SINK}"'"' | sed -e s+"^.* volume=\"\([0-9]*\)\" .*$"+'\1'+)

ACTION="$1"

case "${ACTION}" in
    list)
        printf "auto\tauto\n"
        LANG=C pactl list sinks-raw | sed -e s+"^sink=\"[0-9]*\" name=\"\([^ ]*\)\" .* description=\"\(.*\)\"$"+"\1\t\2"+
        ;;

    get)
        /usr/bin/knulli-settings-get audio.device
        ;;

    set)
        MODE="$2"
        case "${MODE}" in
            auto)
                BT_SINK=$(LANG=C pactl list short sinks | awk '$2 ~ /^bluez_/ { print $2; exit }')
                if [ -n "$BT_SINK" ]; then
                    MODE="$BT_SINK"
                    LANG=C pactl set-default-sink "${MODE}" || exit 1

                    # Workaround to some race coniditons for BT sinks
                    for _ in 1 2 3 4 5; do
                        LANG=C pactl list short sinks | awk '{print $2}' | grep -qx "${MODE}" && break
                        sleep 0.2
                    done
                    LANG=C pactl set-sink-mute "${MODE}" 0 >/dev/null 2>&1 || true
                else
                    ARCH=$(cat /usr/share/knulli/knulli.arch)
                    BOARD=$(cat /boot/boot/knulli.board)

                    case "${ARCH}" in
                        "rk3399")
                            MODE=alsa_output.platform-hdmi-sound.stereo-fallback
                            LANG=C pactl set-default-sink "${MODE}" || exit 1
                            ;;
                        "s922x")
                            if [[ "$BOARD" == "ogu" ]]; then
                                LANG=C pactl set-default-sink INTERNAL
                                amixer -c 0 -q sset "Master" 100%
                                amixer -c 0 sset 'Playback Mux' SPK
                                amixer -c 0 -q sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
                                amixer -c 0 -q sset 'FRDDR_A SRC 1 EN' 'on'
                            fi
                            ;;
                        "rk3326")
                            if [[ "$BOARD" == "r36s" ]]; then
                                amixer -c 0 sset "Playback Path" "SPK_HP"
                            else
                                LANG=C pactl set-default-sink INTERNAL
                                amixer -c 0 cset name='Playback Path' SPK
                            fi
                            ;;
                        "h700")
                            # Needed if booted with hdmi cable plugged in
                            HDMI_STATE="$(cat /sys/devices/platform/soc/6000000.hdmi/extcon/hdmi/state)"
                            if [ "$HDMI_STATE" = "HDMI=1" ]; then
                                MODE=alsa_output._sys_devices_platform_soc_soc_03000000_ahub1_mach_sound_card2.stereo-fallback
                            else
                                MODE=alsa_output._sys_devices_platform_soc_soc_03000000_codec_mach_sound_card0.stereo-fallback
                            fi
                            amixer -c 0 sset "OutputL Mixer DACL" on
                            amixer -c 0 sset "OutputL Mixer DACR" off
                            amixer -c 0 sset "OutputR Mixer DACL" off
                            amixer -c 0 sset "OutputR Mixer DACR" on
                            amixer -c 0 sset LINEOUT on
                            LANG=C pactl set-default-sink "${MODE}" || exit 1
                            ;;
                        "a133")
                            MODE=alsa_output._sys_devices_platform_soc_sndcodec_sound_card0.playback.0.0
                            amixer -c 0 sset 'HpSpeaker' on
                            amixer -c 0 sset 'Headphone' on
                            amixer -c 0 sset Headphone "$(knulli-settings-get audio.headphone || echo 0)"
                            amixer -c 0 sset 'ADC volume' 0
                            amixer -c 0 sset 'LINEOUT volume' 0

                            amixer -c 0 sset 'DAC Swap' Off # Fixes reversed audio channels

                            LANG=C pactl set-default-sink "${MODE}" || exit 1
                            ;;
                        "a527")
                            MODE=alsa_output._sys_devices_platform_soc_3000000_soc_3000000_codec_mach_sound_card0.playback.0.0

                            amixer -c 0 sset 'SPK' on
                            amixer -c 0 sset 'HPOUT' on
                            amixer -c 0 sset 'LINEOUTL' on
                            amixer -c 0 sset 'LINEOUTR' on

                            amixer -c 0 sset 'HPOUT Gain' "$(knulli-settings-get audio.headphone || echo 5)"
                            amixer -c 0 sset 'LINEOUT Gain' 23

                            amixer -c 0 sset 'DACL DACR Swap' On # Fixes reversed audio channels

                            LANG=C pactl set-default-sink "${MODE}" || exit 1
                            ;;
                        "rk3568")
                            if [ -f "/sys/class/drm/card0-HDMI-A-1/status" ]; then
                                read -r HDMI_STATE < "/sys/class/drm/card0-HDMI-A-1/status"
                            fi

                            if [ "$HDMI_STATE" = "connected" ]; then
                                MODE=alsa_output._sys_devices_platform_hdmi-sound_sound_card1.stereo-fallback
                            else
                                MODE=alsa_output._sys_devices_platform_rk817-sound_sound_card0.stereo-fallback
                            fi

                            if [[ "$BOARD" == "powkiddy-rgb30" ]]; then
                                amixer -c 0 sset "Playback Path" "HP"
                            fi

                            # Needed for audio resume after suspend
                            amixer -c 0 sset 'Resume Path' 'ON'
                            LANG=C pactl set-default-sink "${MODE}" || exit 1
                            ;;
                        "sm8250")
                            # boost max volume a bit
                            amixer -c 0 sset 'WSA_RX0 Digital' 112
                            amixer -c 0 sset 'WSA_RX1 Digital' 112
                            ;;
                        *)
                            # do nothing!
                            ;;
                    esac
                fi
                ;;
            *)
                LANG=C pactl set-default-sink "${MODE}" || exit 1
                if [[ $(LANG=C pactl get-default-sink) != "${MODE}" ]]; then
                    # default-sink didn't switch right away for some reason, try again later
                    exit 1
                fi
                ;;
        esac
        ;;

    list-profiles)
        printf "auto\tauto\n"
        LANG=C pactl list cards-profiles-raw | grep 'available="1"' | sed -E 's/^card="[0-9]+" name="(.*)" profile="(.*)" available="[01]" active="[01]" description="(.*)"$/\2@\1\t\3/'
        ;;

    get-profile)
        /usr/bin/knulli-settings-get audio.profile
        ;;

    set-profile)
        MODE="$2"
        if [[ "${MODE}" != "auto" ]]; then
            if knulli-audio list-profiles | grep -q "${MODE}"; then
                PROFILE_NAME=$(echo "${MODE}" | cut -d '@' -f 1)
                CARD_NAME=$(echo "${MODE}" | cut -d '@' -f 2)
                LANG=C pactl set-card-profile "${CARD_NAME}" "${PROFILE_NAME}" || exit 1
            else
                # the profile isn't available yet, try again later
                exit 1
            fi
        fi
        ;;

    getSystemVolume)
        echo "${DETECT_VOLUME}"
        ;;

    setSystemVolume)
        VOLUME="$2"
        case "${VOLUME}" in
            "mute")
                LANG=C pactl set-sink-mute @DEFAULT_SINK@ 1 || exit 1
                ;;
            "unmute")
                LANG=C pactl set-sink-mute @DEFAULT_SINK@ 0 || exit 1
                ;;
            "mute-toggle")
                LANG=C pactl set-sink-mute @DEFAULT_SINK@ toggle || exit 1
                ;;
            *)
                if echo "${VOLUME}" | grep -qE '^[0-9]+$'; then
                    if [[ "${VOLUME}" -ge 0 && "${VOLUME}" -le "${MAX_VOLUME}" ]]; then
                        LANG=C pactl set-sink-volume @DEFAULT_SINK@ "${VOLUME}%" || exit 1
                        exit 0
                    fi
                elif echo "${VOLUME}" | grep -qE '^[+-][0-9]+$'; then
                    let NEW_VOLUME=${DETECT_VOLUME}${VOLUME}
                    NEW_VOLUME=$(( NEW_VOLUME < 0 ? 0 : (NEW_VOLUME > MAX_VOLUME ? MAX_VOLUME : NEW_VOLUME) ))
                    LANG=C pactl set-sink-volume @DEFAULT_SINK@ "${NEW_VOLUME}%" || exit 1
                    exit 0
                fi
                echo "invalid volume value" >&2
                exit 1
                ;;
        esac
        ;;

    test)
        aplay "/usr/share/sounds/stereo-test.wav" || exit 1
        ;;
    *)
        do_usage "$(basename "$0")"
esac
