KEY_VOLUMEUP 1               /usr/bin/volume-button volup
KEY_VOLUMEDOWN 1             /usr/bin/volume-button voldown
KEY_VOLUMEUP 0               /usr/bin/volume-button-release
KEY_VOLUMEDOWN 0             /usr/bin/volume-button-release
KEY_VOLUMEUP+BTN_MODE 1      /usr/bin/volume-button briup
KEY_VOLUMEDOWN+BTN_MODE 1    /usr/bin/volume-button bridown
KEY_VOLUMEUP+BTN_MODE 0      /usr/bin/volume-button-release
KEY_VOLUMEDOWN+BTN_MODE 0    /usr/bin/volume-button-release
BTN_TL+BTN_TRIGGER_HAPPY1 1  /usr/bin/knulli-game-switcher
KEY_POWER 1                  /usr/bin/power-button
KEY_POWER 0                  /usr/bin/power-button-release
KEY_POWER+BTN_MODE 1         /usr/bin/knulli-power-led cycle
BTN_START+BTN_MODE 1         /usr/bin/knulli-softreset
KEY_F12 1		     /usr/bin/lid-control close
KEY_F12 0 		     /usr/bin/lid-control open
