default:
  shader: sharp-shimmerless/shaders_glsl/sharp-shimmerless-scanlines

gamegear:
  shader: presets/sharp-shimmerless-lcd1x
gameandwatch:
  shader: presets/sharp-shimmerless-lcd1x
gb: 
  shader: presets/sharp-shimmerless-lcd1x
gba: 
  shader: presets/sharp-shimmerless-lcd1x
gbc:
  shader: presets/sharp-shimmerless-lcd1x
virtualboy: 
  shader: presets/sharp-shimmerless-lcd1x
ds:
  shader: presets/sharp-shimmerless-lcd1x
lynx:
  shader: presets/sharp-shimmerless-lcd1x
gamate:
  shader: presets/sharp-shimmerless-lcd1x
gmaster:
  shader: presets/sharp-shimmerless-lcd1x
supervision:
  shader: presets/sharp-shimmerless-lcd1x
megaduck: 
  shader: presets/sharp-shimmerless-lcd1x
gamecom:
  shader: presets/sharp-shimmerless-lcd1x
ngpc:
  shader: presets/sharp-shimmerless-lcd1x
ngp:
  shader: presets/sharp-shimmerless-lcd1x
wswan:
  shader: presets/sharp-shimmerless-lcd1x
wswanc:
  shader: presets/sharp-shimmerless-lcd1x
gp32:
  shader: presets/sharp-shimmerless-lcd1x
arduboy:
  shader: presets/sharp-shimmerless-lcd1x
lowresnx:
  shader: presets/sharp-shimmerless-lcd1x

pokemini:
  shader: none
lutro:
  shader: none
pico8:
  shader: none
tic80:
  shader: none
uzebox:
  shader: none
vircon32:
  shader: none
scummvm:
  shader: none
gameandwatch:
  shader: none
lcdgames:
  shader: none  
