#!/bin/sh

# We only want to run the script if the board has RGB capability
if ! knulli-board-capability "rgb"; then
    exit 1
fi

PCT=$1

if [ -n "$PCT" ]; then
  curl -d "$PCT Discharging" -X POST localhost:1235/update-battery-state >/dev/null 2>&1
fi

exit 0
