#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
read -r BOARD < /boot/boot/knulli.board
read -r ARCH  < /usr/share/knulli/knulli.arch
read -r MODEL < /sys/firmware/devicetree/base/model

# Only continue if board and arch match
if [ "$BOARD" = "$ARCH" ]; then
    case "$MODEL" in
        "Retroid Pocket 5")
            mount -o remount,rw /boot
            echo "rp5" > /boot/boot/knulli.board
            sync
            mount -o remount,ro /boot
            ;;
    esac
fi

for i in /etc/init.d/S??* ; do

    # Ignore dangling symlinks (if any).
    [ ! -f "$i" ] && continue

    # Update status for progress bar
    echo "$i" > /tmp/status.txt

    case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            ) &
            ;;
        *)
            case "$i" in
                *S00bootcustom | *S01dbus | *S02resize | *S03modules | *S04populate | *S05udev | *S06audio | *S06modprobe | *S11share | *S12populateshare) # Don't run these in background
                    $i start
                    ;;
                *)
                    $i start &
                    ;;
            esac
            ;;
    esac

    echo QUIT > /tmp/status.txt
    echo $(date +"%F %T,%3N")": ${i} - started" >> /var/run/boot.log
done

exit 0
