DEFAULT rgb30-v1

# Default label for HW-v1 boards (tcs4525 at i2c0 0x1c).
LABEL rgb30-v1
    LINUX /boot/linux
    FDT /boot/rk3566-rgb30-linux.dtb
    APPEND initrd=/boot/initrd.lz4 label=KNULLI rootwait quiet loglevel=0 console=tty3 console=ttyS2,1500000n8 fbcon=rotate:0

# Selected by u-boot via pxe_label_override when tcs4525 is detected
# at i2c0 0x40 (HW-v2 boards).
LABEL rgb30-v2
    LINUX /boot/linux
    FDT /boot/rk3566-rgb30-v2-linux.dtb
    APPEND initrd=/boot/initrd.lz4 label=KNULLI rootwait quiet loglevel=0 console=tty3 console=ttyS2,1500000n8 fbcon=rotate:0
